### ISSUE TITLE
2 broken links at http://pep8.org/#function-annotations

### ISSUE THREAD

**Issue by denis-trofimov** [kennethreitz/pep8.org#10]
At chapter http://pep8.org/#function-annotations:
first line of the chapter and 1st line of 2nd paragraph have broken links "http://pep8.org/pep%20484".

**Comment by kennethreitz** [comment]
could you send a pull request?

**Comment by denis-trofimov** [comment]
HI!
I don't know how the links are generated like this:  [https://www.python.org/dev/peps/pep-0484/](https://www.python.org/dev/peps/pep-0484/) 
I have checked pep8.html, it is seems OK.
I have looked in  JS files - it is hard to find.
