### ISSUE TITLE
TOC wrapped-header line spacing too large

### ISSUE THREAD

**Issue by nicktimko** [kennethreitz/pep8.org#11]
`.toc-link.h1` has a `line-spacing` in it that makes wrapped heading names hard to visually see what's one or two. Without mouse-over highlighting, the 3 headings looks like 4.

![screen shot 2017-03-15 at 11 22 20](https://cloud.githubusercontent.com/assets/5297556/23958939/b38734dc-0971-11e7-9992-88591211656c.png)

I'm white-belt in CSS-fu, but something like a margin/padding to split up the headers while reducing the line spacing tightens up wrapped-headers but keeps the inter-header-spacing.

![screen shot 2017-03-15 at 11 21 53](https://cloud.githubusercontent.com/assets/5297556/23958954/bf1bb278-0971-11e7-8b2c-995affe422aa.png)

**Comment by kennethreitz** [comment]
send a PR!

**Comment by nicktimko** [comment]
Was going to say that I don't have Node 93.4253 installed with dependency manager Blower 7434.534alpha42 to get LASS release Kilo-Kid, so couldn't rebuild, but it's just boring old CSS...so probably can.

**Comment by nicktimko** [comment]
PR made ( #12 ), does it look good/bad/ugly? Comments?
