### ISSUE TITLE
SSL Certificate Hostname Mismatch

### ISSUE THREAD

**Issue by ghost** [kennethreitz/pep8.org#13]
There is a bit of an issue with the site.

Your SSL Cert appears to have an issue. Best guess to me (and the browser) is there is a hostname mismatch:

![Screenshot: https://pep8.org](https://cloud.githubusercontent.com/assets/16548240/24589801/cc95e00e-1795-11e7-9cbf-f7d224a6211c.png)

Perhaps something in Heroku needs a change? 

I know this isn't a *huge* issue, certainly. Just think it would be relatively trivial to fix? I just figured you might want to be aware, especially since the site will always throw an error for anyone who automatically re-directs all traffic to https://* (such as myself, wherever possible). I note that I didn't have an issue in chrome with the extension HTTPS everywhere plugged in, however the FireFox version tried to force it and gave me the same error (I grabbed the screenshot from safari since its the best layout for this sort of thing I find)

**Comment by kennethreitz** [comment]
SSL was never configured. I'm looking into fixing this.

**Comment by kennethreitz** [comment]
I'm going to close this as a non-issue for now.
