### ISSUE TITLE
Please update your binary operator line break

### ISSUE THREAD

**Issue by jcrmatos** [kennethreitz/pep8.org#14]
Hello,

Binary operator line break was changed in PEP8, please update your beautiful guide.
Check section "Should a line break before or after a binary operator? " in PEP8.

Best regards,

JM

**Comment by kennethreitz** [comment]
could you send a pull request?

**Comment by dbader** [comment]
FYI this relates to #15 and was fixed in #16.

**Comment by kennethreitz** [comment]
thanks @dbader!
