### ISSUE TITLE
Sync latest PEP 8 changes

### ISSUE THREAD

**Issue by dbader** [kennethreitz/pep8.org#15]
Hey @kennethreitz, I love your work and I've been referring people to pep8.org every time someone asked for an "easier to read" representation of the original PEP 8.

As per our conversation at PyCon I'd love to help with keeping pep8.org up to date and I'm planning to submit a PR that pulls in the latest changes from the [original pep-0008.txt](https://hg.python.org/peps/log/tip/pep-0008.txt) file.

Looking at the [hg history for the original PEP 8](https://hg.python.org/peps/log/tip/pep-0008.txt) and comparing it with what's live on pep8.org, the latest changeset that was migrated to pep8.org is this one: https://hg.python.org/peps/rev/19ef54ed6aaa

There are several changes that happened after that and I'll put together a pull-request to make those updates over the next few days. This issue is mainly a mutex to avoid duplicate work. 

If you think what I wrote makes sense there's no need to reply and I'll ping you once I've got the PR ready. Thanks again for running pep8.org!

— Dan

**Comment by kennethreitz** [comment]
Fantastic news! I'll add you to the repo :)

**Comment by kennethreitz** [comment]
I think we're using Heroku for deployment. Can you send me your Heroku email address if you have one?

**Comment by kennethreitz** [comment]
I can setup auto deploys actually

**Comment by dbader** [comment]
> Fantastic news! I'll add you to the repo :)

Great, thanks :)

My Heroku email address is mail@dbader.org.

**Comment by kennethreitz** [comment]
the app automatically deploys from the master branch now :)

**Comment by dbader** [comment]
> the app automatically deploys from the master branch now :)

Great, I just triggered an auto-deploy and the latest changes are live now. Cheers Kenneth :)

**Comment by kennethreitz** [comment]
✨🍰✨

**Comment by KPilnacek** [comment]
Hello @dbader and @kennethreitz,

I like this page very much but it was pointed out to me that it is outdated (section [When to use trailing commas](https://www.python.org/dev/peps/pep-0008/#when-to-use-trailing-commas) is missing) in comparison with the official pep8. It was added by Guido this February, see the [history of commits](https://github.com/python/peps/commits/master/pep-0008.txt). It seems to be a problem with the source repo as you use the mercurial repo not the github.
I will be happy to be of assistance, but I'm not sure how to do it :) (completely new to opensource...).

Krystof

**Comment by kennethreitz** [comment]
Gotta do it by hand! @dbader was doing this for a while — you can send a pull request though!

**Comment by KPilnacek** [comment]
OK then, I'll send one, however, it'll take some time :).
