### ISSUE TITLE
Wide code block looks odd

### ISSUE THREAD

**Issue by hackebrot** [kennethreitz/pep8.org#2]
Hi @kennethreitz :wave:

I noticed that code blocks do not always show a horizontal scroll-bar (see [Function Annotations](http://pep8.org/#function-annotations)):
<img width="710" alt="screen shot 2016-02-21 at 19 33 06" src="https://cloud.githubusercontent.com/assets/6024445/13204872/ad232928-d8d2-11e5-82d6-391753c03487.png">

At first glance it looks broken until you find out that you can actually scroll to inspect the full line.

I think it makes sense to always show the scroll-bar or find a better way of indicating that there's more code if you scroll to the right.

Nice fonts :smile_cat: 

**Update**: Specs OS X 10.11.3, Firefox 44.0.2

**Comment by kennethreitz** [comment]
That's my least favorite code-block on this whole document :)

Hmmm, it renders fine for me. Exact same versions of OS X and Firefox:

<img width="790" alt="screen shot 2016-02-21 at 2 57 40 pm-1" src="https://cloud.githubusercontent.com/assets/119893/13205023/9edd081a-d8ab-11e5-8285-227287337fb4.png">

**Comment by hackebrot** [comment]
Does it show the scroll-bar without focus though?

**Comment by kennethreitz** [comment]
Yes, it's always there.

**Comment by hackebrot** [comment]
:scream:

**Comment by hackebrot** [comment]
<img width="718" alt="screen shot 2016-02-21 at 20 01 33" src="https://cloud.githubusercontent.com/assets/6024445/13205044/fc9033ea-d8d5-11e5-9c53-4f04ea7f6629.png">

**Comment by kennethreitz** [comment]
I have no idea why this is happening, and cannot reproduce. 

I'm beginning to remember why I don't do frontend development anymore :)

**Comment by hackebrot** [comment]
Haha, no worries.

**Comment by kriwil** [comment]
could it be the OS X settings?

![screenshot 2016-02-22 07 36 35](https://cloud.githubusercontent.com/assets/15750/13206738/0c7740e4-d937-11e5-81fc-54681d0dbc83.png)

**Comment by hackebrot** [comment]
That's the setting I'm using. :grin:

**Comment by kennethreitz** [comment]
That's the setting I'm using. :8ball: 

I am, however, using a real mouse.

**Comment by hackebrot** [comment]
Uhhm..plugging in the mouse actually...solved this :open_mouth:

**Comment by kennethreitz** [comment]
haha! There must be some CSS we can use to trigger that behavior.

**Comment by kennethreitz** [comment]
https://twitter.com/nickhudkins/status/701575890501767169
