### ISSUE TITLE
margin-top of .toc pushes the bottom part of TOC off the screen

### ISSUE THREAD

**Issue by s9v** [kennethreitz/pep8.org#25]
The lowest part of Table of Contents is not visible when you scroll all the way down.

![1](https://user-images.githubusercontent.com/3767237/40273550-d6eaee12-5bfc-11e8-9173-f6d723a7cf67.PNG)

Removing `margin-top` from `.toc` fixes it.

![2](https://user-images.githubusercontent.com/3767237/40273566-53d4b6ec-5bfd-11e8-84bb-e3eed0abcb77.PNG)

**Comment by BramVer** [comment]
On firefox-developers-edition 64.0b3:  

Fix doesn't seem to be live yet :)
![image](https://user-images.githubusercontent.com/16743200/47501784-a1f12780-d866-11e8-98f4-b874f9c818df.png)
