### ISSUE TITLE
Confusing font used for code comments

### ISSUE THREAD

**Issue by salty-horse** [kennethreitz/pep8.org#7]
Code blocks on pep8.org use the font "Operator Mono".

Comments in the code blocks are italicized. The italicized font is significantly different than the regular unstyled form. Specifically, it is in faux-cursive, with "r", "s", "f", "l" written in their cursive form, while still being monospace, with the letters separate from each other. Lower-case "L" in particular looks a lot like "e", as they are both almost the same height.

IMO as a non-native speaker/reader of English, this reduces the readability of the text.
This is totally subjective. I'm reporting this in case it bothers others.

**Comment by kennethreitz** [comment]
this font is beautiful :)

**Comment by amrishparmar** [comment]
I would suggest that this be reopened. It may be subjectively considered "beautiful", but it be very difficult to read for those with dyslexia and, as @salty-horse points out, those who are non-native speakers/readers. Given that part of the point of this site is to be "for humans" I'd suggest reconsidering. To quote The Zen of Python, "Readability counts".
