### ISSUE TITLE
pep8 update!

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/pep8.org#8]
https://groups.google.com/forum/#!topic/dev-python/XsapBulcleU

**Comment by zoidyzoidzoid** [comment]
Coming here from [pycodestyle](https://github.com/PyCQA/pycodestyle/issues/466#issuecomment-224496073)

Running `curl -s https://hg.python.org/peps/raw-file/tip/pep-0008.txt | pandoc -S --toc --from rst --to html -o index.html` gets us pretty close as visible [here](https://github.com/zoidbergwill/pep8.org/commit/250f882f9ce797689a44973f50d3e48b40def293)

`pandoc` has some useful args that could get us a bit further too:

```
  -H FILENAME           --include-in-header=FILENAME
  -B FILENAME           --include-before-body=FILENAME
  -A FILENAME           --include-after-body=FILENAME
```

Will see how much those help.

However stripping some of the raw file's header will probably be necessary too, which we might be able to do with `sed` or something.

I'm not sure if there are simpler/easier ways?

**Comment by FichteFoll** [comment]
\*push\*

I like pep8.org in that it's much easier to read, but the fact that it is still outdated is kind of bad. An automated fetching script would be nice.

**Comment by kennethreitz** [comment]
i did update it recently

**Comment by FichteFoll** [comment]
I was looking for https://www.python.org/dev/peps/pep-0008/#module-level-dunder-names, which is missing currently. I don't remember what this issue was about initially, sorry.

**Comment by kennethreitz** [comment]
pull requests accepted (and welcomed!)

**Comment by kennethreitz** [comment]
unfortunately, an automated import undoes the full day of manual patching i did to the html to make it render nicely

**Comment by kennethreitz** [comment]
so, manual updates must be added
