### ISSUE TITLE
Font issue with headings on MacOS X with Safari

### ISSUE THREAD

**Issue by astrofrog** [kennethreitz/pep8.org#9]
This does not occur with Chrome and Firefox, only Safari. I am using MacOS X 10.11

![screen shot 2016-05-31 at 15 32 41](https://cloud.githubusercontent.com/assets/314716/15678167/2b193f46-2745-11e6-9ad4-f94bba39fcc8.png)

**Comment by haikuginger** [comment]
From what I can tell on this, it seems like there are characters that aren't available in the small-caps style for "Operator A", and Safari isn't falling back on "Operator B" to render them. You can see the side-effects of this by removing either Operator A or Operator B in turn from the `h1` node in the in-page CSS in Firefox - some characters get rendered in a default serif font.
